"""Update user model

Revision ID: 0a73f874352d
Revises: 389fdfebab65
Create Date: 2024-09-30 14:57:29.065680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a73f874352d'
down_revision: Union[str, None] = '389fdfebab65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('user', 'tg_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
