"""Add new model: contact_manager

Revision ID: 389fdfebab65
Revises: e15690914928
Create Date: 2024-09-27 13:45:33.565833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389fdfebab65'
down_revision: Union[str, None] = 'e15690914928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactmanager',
    sa.Column('first_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=25), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactmanager')
    # ### end Alembic commands ###
