"""Merge 2 direction

Revision ID: d2365dc6d2ca
Revises: 31916cbb37e1
Create Date: 2024-10-07 12:56:05.967698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2365dc6d2ca'
down_revision: Union[str, None] = '31916cbb37e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.TEXT(), nullable=False),
    sa.Column('feedback_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('unread', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('categorytype_product_id_fkey', 'categorytype', type_='foreignkey')
    op.create_foreign_key(None, 'categorytype', 'productcategory', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('contactmanager', sa.Column('shipping_date_close', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contactmanager', 'shipping_date_close')
    op.drop_constraint(None, 'categorytype', type_='foreignkey')
    op.create_foreign_key('categorytype_product_id_fkey', 'categorytype', 'productcategory', ['product_id'], ['id'])
    op.drop_table('feedback')
    # ### end Alembic commands ###
