"""First migration

Revision ID: e15690914928
Revises: 
Create Date: 2024-09-26 23:48:22.126438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e15690914928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkcompanyportfolio',
    sa.Column('project_name', sa.VARCHAR(length=48), nullable=False),
    sa.Column('url', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info',
    sa.Column('question_type', postgresql.ENUM('TOPIC_1', 'TOPIC_2', 'TOPIC_3', name='question_enum'), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('informationaboutcompany',
    sa.Column('name', sa.VARCHAR(length=48), nullable=False),
    sa.Column('url', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productcategory',
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('tg_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=25), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'MANAGER', name='role_enum'), nullable=False),
    sa.Column('join_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('categorytype',
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=64), nullable=False),
    sa.Column('media', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['productcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorytype_product_id'), 'categorytype', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorytype_product_id'), table_name='categorytype')
    op.drop_table('categorytype')
    op.drop_table('user')
    op.drop_table('productcategory')
    op.drop_table('informationaboutcompany')
    op.drop_table('info')
    op.drop_table('checkcompanyportfolio')
    # ### end Alembic commands ###
