"""add description fields to product and category, rename RoleEnum

Revision ID: 4c3a4964ff61
Revises: 42e8d0d2bdd4
Create Date: 2024-10-13 16:09:40.786385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3a4964ff61'
down_revision: Union[str, None] = '42e8d0d2bdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorytype', sa.Column('description', sa.TEXT(), nullable=False))
    op.add_column('productcategory', sa.Column('description', sa.TEXT(), nullable=False))
    op.drop_column('productcategory', 'response')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productcategory', sa.Column('response', sa.TEXT(), nullable=False))
    op.drop_column('productcategory', 'description')
    op.drop_column('categorytype', 'description')
    # ### end Alembic commands ###
