"""add timer

Revision ID: 4f7c029c89f4
Revises: 17c3c5e67c14
Create Date: 2024-10-18 00:20:36.194500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7c029c89f4'
down_revision: Union[str, None] = '17c3c5e67c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('timer', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('categorytype', 'media',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('checkcompanyportfolio', 'name',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('contactmanager', 'phone_number',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('informationaboutcompany', 'name',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('informationaboutcompany', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.VARCHAR(length=48),
               existing_nullable=False)
    op.alter_column('contactmanager', 'phone_number',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('checkcompanyportfolio', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.VARCHAR(length=48),
               existing_nullable=False)
    op.alter_column('categorytype', 'media',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_table('timer')
    # ### end Alembic commands ###
