"""Update Feedback

Revision ID: fd795bdbba90
Revises: 
Create Date: 2024-10-11 19:56:11.060934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd795bdbba90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('feedback_text', sa.TEXT(), nullable=False),
    sa.Column('feedback_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('unread', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
